services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: videoflow
    volumes:
      - videoflow_postgres_data:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker -d videoflow']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - videoflow_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  videoflow_postgres_data:
  videoflow_redis_data:
